import { createContext, useContext, useState } from "react";

export const LANGS = {
  en: {
    // Nav & General
    home: "Home",
    progress: "Progress",
    voice: "Voice",
    alerts: "Alerts",
    diet: "Diet",
    dashboard: "Dashboard",
    tools: "Tools",
    hospitals: "Hospitals",
    save: "Save",
    savedLocally: "Saved Locally",
    logOut: "Log Out",
    signOut: "Sign Out",
    loading: "Please wait...",
    
    // Auth
    welcomeBack: "Welcome Back",
    createAccount: "Create Account",
    fullName: "Full Name",
    phoneNumber: "Phone Number",
    password: "Password",
    role: "Role",
    language: "Language",
    patientRole: "Patient (Expecting Mother)",
    ashaRole: "ASHA Worker",
    logIn: "Log In",
    signUp: "Sign Up",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    
    // Progress
    youAre: "You are",
    week: "Week",
    trimester: "Trimester",
    babySize: "Baby is the size of a",
    estimatedDueDate: "Estimated Due Date",
    kickCounter: "Kick Counter",
    weeklyInsight: "Weekly Insight",
    
    // Dashboard / Health
    myHealth: "My Health",
    healthHistory: "Health History",
    noSymptomLogs: "No symptom logs yet",
    risk: "Risk Level",
    suggestion: "Suggestion",
    ashaWorker: "ASHA Worker",
    patientSymptomReports: "Patient Symptom Reports",
    assignedPatients: "Assigned Patients",
    visitRecords: "Visit Records",
    schedule: "Schedule",
    
    // Hospitals
    nearbyHospitals: "Nearby Hospitals",
    getDirections: "Get Directions",
    findingLocation: "Finding your location...",
    sos: "SOS Alert",
  },
  hi: {
    home: "होम",
    progress: "प्रगति",
    voice: "आवाज",
    alerts: "अलर्ट",
    diet: "आहार",
    dashboard: "डैशबोर्ड",
    tools: "उपकरण",
    hospitals: "अस्पताल",
    save: "सहेजें",
    savedLocally: "स्थानीय रूप से सहेजा गया",
    logOut: "लॉग आउट",
    signOut: "साइन आउट",
    loading: "कृपया प्रतीक्षा करें...",
    
    welcomeBack: "वापसी पर स्वागत है",
    createAccount: "खाता बनाएं",
    fullName: "पूरा नाम",
    phoneNumber: "फ़ोन नंबर",
    password: "पासवर्ड",
    role: "भूमिका",
    language: "भाषा",
    patientRole: "मरीज (गर्भवती महिला)",
    ashaRole: "आशा कार्यकर्ता",
    logIn: "लॉग इन करें",
    signUp: "साइन अप करें",
    alreadyHaveAccount: "पहले से ही एक खाता है?",
    dontHaveAccount: "खाता नहीं है?",
    
    youAre: "आप हैं",
    week: "सप्ताह",
    trimester: "तिमाही",
    babySize: "बच्चा इस आकार का है",
    estimatedDueDate: "अनुमानित नियत तारीख",
    kickCounter: "किक काउंटर",
    weeklyInsight: "साप्ताहिक अंतर्दृष्टि",
    
    myHealth: "मेरा स्वास्थ्य",
    healthHistory: "स्वास्थ्य इतिहास",
    noSymptomLogs: "अभी तक कोई लक्षण लॉग नहीं है",
    risk: "जोखिम स्तर",
    suggestion: "सुझाव",
    ashaWorker: "आशा कार्यकर्ता",
    patientSymptomReports: "मरीज के लक्षण रिपोर्ट",
    assignedPatients: "सौंपे गए मरीज",
    visitRecords: "विजिट रिकॉर्ड",
    schedule: "शेड्यूल",
    
    nearbyHospitals: "नजदीकी अस्पताल",
    getDirections: "दिशा-निर्देश प्राप्त करें",
    findingLocation: "आपका स्थान खोज रहे हैं...",
    sos: "SOS अलर्ट",
  },
  te: {
    home: "హోమ్",
    progress: "పురోగతి",
    voice: "వాయిస్",
    alerts: "హెచ్చరికలు",
    diet: "ఆహారం",
    dashboard: "డాష్‌బోర్డ్",
    tools: "సాధనాలు",
    hospitals: "ఆసుపత్రులు",
    save: "సేవ్",
    savedLocally: "లోకల్‌గా సేవ్ అయింది",
    logOut: "లాగ్ అవుట్",
    signOut: "సైన్ అవుట్",
    loading: "వేచి ఉండండి...",
    
    welcomeBack: "తిరిగి స్వాగతం",
    createAccount: "ఖాతా సృష్టించండి",
    fullName: "పూర్తి పేరు",
    phoneNumber: "ఫోన్ నంబర్",
    password: "పాస్‌వర్డ్",
    role: "పాత్ర",
    language: "భాష",
    patientRole: "రోగి (గర్భిణీ స్త్రీ)",
    ashaRole: "ఆశా కార్యకర్త",
    logIn: "లాగిన్",
    signUp: "సైన్ అప్",
    alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా?",
    dontHaveAccount: "ఖాతా లేదా?",
    
    youAre: "మీరు",
    week: "వారం",
    trimester: "త్రైమాసికం",
    babySize: "బిడ్డ పరిమాణం",
    estimatedDueDate: "అంచనా తేదీ",
    kickCounter: "కిక్ కౌంటర్",
    weeklyInsight: "వారపు సమాచారం",
    
    myHealth: "నా ఆరోగ్యం",
    healthHistory: "ఆరోగ్య చరిత్ర",
    noSymptomLogs: "ఇంకా లక్షణాల లాగ్‌లు లేవు",
    risk: "ప్రమాద స్థాయి",
    suggestion: "సూచన",
    ashaWorker: "ఆశా కార్యకర్త",
    patientSymptomReports: "రోగి లక్షణ నివేదికలు",
    assignedPatients: "కేటాయించిన రోగులు",
    visitRecords: "సందర్శన రికార్డులు",
    schedule: "షెడ్యూల్",
    
    nearbyHospitals: "సమీప ఆసుపత్రులు",
    getDirections: "దారి చూపించు",
    findingLocation: "మీ స్థానం కనుగొంటున్నాం...",
    sos: "SOS హెచ్చరిక",
  },
  ta: {
    home: "முகப்பு",
    progress: "முன்னேற்றம்",
    voice: "குரல்",
    alerts: "எச்சரிக்கைகள்",
    diet: "உணவு",
    dashboard: "டாஷ்போர்டு",
    tools: "கருவிகள்",
    hospitals: "மருத்துவமனை",
    save: "சேமி",
    savedLocally: "உள்ளூரில் சேமிக்கப்பட்டது",
    logOut: "வெளியேறு",
    signOut: "வெளியேறு",
    loading: "காத்திருக்கவும்...",
    welcomeBack: "மீண்டும் வருக",
    createAccount: "கணக்கை உருவாக்கு",
    fullName: "முழு பெயர்",
    phoneNumber: "தொலைபேசி எண்",
    password: "கடவுச்சொல்",
    role: "பங்கு",
    language: "மொழி",
    patientRole: "நோயாளி (கர்ப்பிணித் தாய்)",
    ashaRole: "ஆஷா பணியாளர்",
    logIn: "உள்நுழை",
    signUp: "பதிவு செய்",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    dontHaveAccount: "கணக்கு இல்லையா?",
    youAre: "நீங்கள்",
    week: "வாரம்",
    trimester: "மும்மாதம்",
    babySize: "குழந்தை அளவு",
    estimatedDueDate: "எதிர்பார்க்கப்படும் தேதி",
    kickCounter: "கிக் கவுண்டர்",
    weeklyInsight: "வாராந்திர நுண்ணறிவு",
    myHealth: "எனது ஆரோக்கியம்",
    healthHistory: "ஆரோக்கிய வரலாறு",
    noSymptomLogs: "இன்னும் அறிகுறிகள் பதிவு செய்யப்படவில்லை",
    risk: "ஆபத்து நிலை",
    suggestion: "பரிந்துரை",
    ashaWorker: "ஆஷா பணியாளர்",
    patientSymptomReports: "நோயாளி அறிகுறிகள் அறிக்கை",
    assignedPatients: "ஒதுக்கப்பட்ட நோயாளிகள்",
    visitRecords: "சந்திப்பு பதிவுகள்",
    schedule: "திட்டமிடு",
    nearbyHospitals: "அருகிலுள்ள மருத்துவமனைகள்",
    getDirections: "வழி காட்டு",
    findingLocation: "உங்கள் இடத்தை தேடுகிறோம்...",
    sos: "SOS எச்சரிக்கை",
  },
  kn: {
    home: "ಮನೆ",
    progress: "ಪ್ರಗತಿ",
    voice: "ಧ್ವನಿ",
    alerts: "ಎಚ್ಚರಿಕೆಗಳು",
    diet: "ಆಹಾರ",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    tools: "ಸಾಧನಗಳು",
    hospitals: "ಆಸ್ಪತ್ರೆ",
    save: "ಉಳಿಸಿ",
    savedLocally: "ಸ್ಥಳೀಯವಾಗಿ ಉಳಿಸಲಾಗಿದೆ",
    logOut: "ಲಾಗ್ ಔಟ್",
    signOut: "ಸೈನ್ ಔಟ್",
    loading: "ದಯವಿಟ್ಟು ಕಾಯಿರಿ...",
    welcomeBack: "ಮರಳಿ ಸ್ವಾಗತ",
    createAccount: "ಖಾತೆ ರಚಿಸಿ",
    fullName: "ಪೂರ್ಣ ಹೆಸರು",
    phoneNumber: "ಫೋನ್ ಸಂಖ್ಯೆ",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    role: "ಪಾತ್ರ",
    language: "ಭಾಷೆ",
    patientRole: "ರೋಗಿ (ಗರ್ಭಿಣಿ ತಾಯಿ)",
    ashaRole: "ಆಶಾ ಕಾರ್ಯಕರ್ತೆ",
    logIn: "ಲಾಗಿನ್",
    signUp: "ಸೈನ್ ಅಪ್",
    alreadyHaveAccount: "ಖಾತೆ ಈಗಾಗಲೇ ಇದೆಯೇ?",
    dontHaveAccount: "ಖಾತೆ ಇಲ್ಲವೇ?",
    youAre: "ನೀವು",
    week: "ವಾರ",
    trimester: "ತ್ರೈಮಾಸಿಕ",
    babySize: "ಮಗುವಿನ ಗಾತ್ರ",
    estimatedDueDate: "ಅಂದಾಜು ದಿನಾಂಕ",
    kickCounter: "ಕಿಕ್ ಕೌಂಟರ್",
    weeklyInsight: "ಸಾಪ್ತಾಹಿಕ ಒಳನೋಟ",
    myHealth: "ನನ್ನ ಆರೋಗ್ಯ",
    healthHistory: "ಆರೋಗ್ಯ ಇತಿಹಾಸ",
    noSymptomLogs: "ಇನ್ನೂ ಯಾವುದೇ ರೋಗಲಕ್ಷಣಗಳಿಲ್ಲ",
    risk: "ಅಪಾಯ ಮಟ್ಟ",
    suggestion: "ಸಲಹೆ",
    ashaWorker: "ಆಶಾ ಕಾರ್ಯಕರ್ತೆ",
    patientSymptomReports: "ರೋಗಲಕ್ಷಣ ವರದಿಗಳು",
    assignedPatients: "ನಿಯೋಜಿತ ರೋಗಿಗಳು",
    visitRecords: "ಭೇಟಿ ದಾಖಲೆಗಳು",
    schedule: "ವೇಳಾಪಟ್ಟಿ",
    nearbyHospitals: "ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳು",
    getDirections: "ದಾರಿ ತೋರಿಸಿ",
    findingLocation: "ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
    sos: "SOS ಎಚ್ಚರಿಕೆ",
  },
  mr: {
    home: "होम",
    progress: "प्रगती",
    voice: "आवाज",
    alerts: "सूचना",
    diet: "आहार",
    dashboard: "डॅशबोर्ड",
    tools: "साधने",
    hospitals: "रुग्णालय",
    save: "जतन करा",
    savedLocally: "स्थानिकरित्या जतन केले",
    logOut: "लॉग आउट",
    signOut: "साइन आउट",
    loading: "कृपया प्रतीक्षा करा...",
    welcomeBack: "परत स्वागत आहे",
    createAccount: "खाते तयार करा",
    fullName: "पूर्ण नाव",
    phoneNumber: "फोन नंबर",
    password: "पासवर्ड",
    role: "भूमिका",
    language: "भाषा",
    patientRole: "रुग्ण (गर्भवती माता)",
    ashaRole: "आशा वर्कर",
    logIn: "लॉग इन",
    signUp: "साइन अप",
    alreadyHaveAccount: "आधीच खाते आहे का?",
    dontHaveAccount: "खाते नाही का?",
    youAre: "तुम्ही",
    week: "आठवडा",
    trimester: "तिमाही",
    babySize: "बाळाचा आकार",
    estimatedDueDate: "अंदाजे देय तारीख",
    kickCounter: "किक काउंटर",
    weeklyInsight: "साप्ताहिक अंतर्दृष्टि",
    myHealth: "माझे आरोग्य",
    healthHistory: "आरोग्य इतिहास",
    noSymptomLogs: "अद्याप कोणतीही लक्षणे नाहीत",
    risk: "धोका पातळी",
    suggestion: "सूचना",
    ashaWorker: "आशा वर्कर",
    patientSymptomReports: "रुग्ण लक्षण अहवाल",
    assignedPatients: "नियुक्त रुग्ण",
    visitRecords: "भेट रेकॉर्ड",
    schedule: "वेळापत्रक",
    nearbyHospitals: "जवळची रुग्णालये",
    getDirections: "मार्ग मिळवा",
    findingLocation: "तुमचे स्थान शोधत आहे...",
    sos: "SOS सूचना",
  },
  bn: {
    home: "হোম",
    progress: "প্রগতি",
    voice: "ভয়েস",
    alerts: "সতর্কতা",
    diet: "খাদ্য",
    dashboard: "ড্যাশবোর্ড",
    tools: "সরঞ্জাম",
    hospitals: "হাসপাতাল",
    save: "সংরক্ষণ",
    savedLocally: "স্থানীয়ভাবে সংরক্ষিত",
    logOut: "লগ আউট",
    signOut: "সাইন আউট",
    loading: "দয়া করে অপেক্ষা করুন...",
    welcomeBack: "ফিরে আসার জন্য স্বাগতম",
    createAccount: "অ্যাকাউন্ট তৈরি করুন",
    fullName: "পুরো নাম",
    phoneNumber: "ফোন নম্বর",
    password: "পাসওয়ার্ড",
    role: "ভূমিকা",
    language: "ভাষা",
    patientRole: "রোগী (গর্ভবতী মা)",
    ashaRole: "আশা কর্মী",
    logIn: "লগ ইন",
    signUp: "সাইন আপ",
    alreadyHaveAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    dontHaveAccount: "অ্যাকাউন্ট নেই?",
    youAre: "আপনি",
    week: "সপ্তাহ",
    trimester: "ত্রৈমাসিক",
    babySize: "বাচ্চার আকার",
    estimatedDueDate: "সম্ভাব্য প্রসবের তারিখ",
    kickCounter: "কিক কাউন্টার",
    weeklyInsight: "সাপ্তাহিক অন্তর্দৃষ্টি",
    myHealth: "আমার স্বাস্থ্য",
    healthHistory: "স্বাস্থ্যের ইতিহাস",
    noSymptomLogs: "এখনো কোনো উপসর্গ নেই",
    risk: "ঝুঁকি স্তর",
    suggestion: "পরামর্শ",
    ashaWorker: "আশা কর্মী",
    patientSymptomReports: "রোগীর উপসর্গের রিপোর্ট",
    assignedPatients: "নিযুক্ত রোগী",
    visitRecords: "সাক্ষাৎকারের রেকর্ড",
    schedule: "তফসিল",
    nearbyHospitals: "কাছের হাসপাতাল",
    getDirections: "পথ দেখান",
    findingLocation: "আপনার অবস্থান খুঁজছি...",
    sos: "SOS সতর্কতা",
  },
};

export type LangKey = keyof typeof LANGS;

export interface LangContextValue {
  lang: LangKey;
  setLang: (l: LangKey) => void;
  t: (typeof LANGS)[LangKey];
}

const LangContext = createContext<LangContextValue>({
  lang: "en",
  setLang: () => {},
  t: LANGS.en,
});

export function LangProvider({ children }: { children: React.ReactNode }) {
  const stored = (localStorage.getItem("pg_lang") ?? "en") as LangKey;
  const [lang, setLangState] = useState<LangKey>(stored);

  function setLang(l: LangKey) {
    setLangState(l);
    localStorage.setItem("pg_lang", l);
  }

  return (
    <LangContext.Provider value={{ lang, setLang, t: LANGS[lang] }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
